"""Bundle metadata (``bundle.json``) schema.

Defines the typed shape of a bundle's metadata side-car, including the
provenance / licensing block that identifies spektrafilm as the source
and surfaces citation expectations to downstream users. I/O lives with
the builder; the dataclasses here are the source of truth for shape.

The provenance defaults mirror :class:`spektrafilm.profiles.io.ProfileMetadata`
so a user receiving a LUT bundle reads the same licensing story they'd
read on the profiles that informed it.

See studies/a40_lut_system/n030_lut_package_design.md §4.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from importlib.metadata import PackageNotFoundError, version as distribution_version
from typing import Any

from spektrafilm_lut_creator.wires import DensityWire, LogEWire


SCHEMA_VERSION = 1

_PROJECT_URL = "https://github.com/andreavolpato/spektrafilm"
_LUT_LICENSE_URL = "https://github.com/andreavolpato/spektrafilm/blob/main/SPEKTRAFILM_LICENSE.txt"


def _spektrafilm_version() -> str:
    """The installed spektrafilm distribution version, or ``0+unknown``."""
    try:
        return distribution_version("spektrafilm")
    except PackageNotFoundError:
        return "0+unknown"


def _created_iso8601() -> str:
    """UTC build timestamp in ISO 8601 (seconds resolution)."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _copyright_statement() -> str:
    return (
        f"Copyright (c) {date.today().year} Andrea Volpato. "
        "Generated by spektrafilm. Licensed under CC BY-SA 4.0."
    )


@dataclass
class ProvenanceMeta:
    """Provenance and licensing information for a LUT bundle.

    Every bundle carries this block so downstream users (colorists,
    grading suites, archive systems) can identify spektrafilm as the
    source, comply with CC BY-SA 4.0 (the license covering spektrafilm
    profiles and their direct derivatives, including this LUT — see
    SPEKTRAFILM_LICENSE.txt shipped alongside the bundle), and cite
    the work correctly. The defaults mirror the spektrafilm profile
    metadata pattern.
    """
    spektrafilm_version: str = field(default_factory=_spektrafilm_version)
    # The LUT creator ships inside the spektrafilm distribution; it
    # has no separate version of its own.
    lut_creator_version: str = field(default_factory=_spektrafilm_version)
    created: str = field(default_factory=_created_iso8601)
    copyright: str = field(default_factory=_copyright_statement)
    license: str = (
        f"spektrafilm LUT by Andrea Volpato, licensed under CC BY-SA 4.0. "
        f"Full text and attribution requirements in SPEKTRAFILM_LICENSE.txt (shipped "
        f"in this bundle); also at {_LUT_LICENSE_URL}."
    )
    citation: str = (
        "If you use this LUT in your work, please cite the spektrafilm "
        f"project: {_PROJECT_URL}, see CITATION.cff for details."
    )
    project_url: str = _PROJECT_URL
    notes: str = (
        "Generated by the spektrafilm LUT bundle builder. Apply with "
        "trilinear or tetrahedral interpolation in your host (DaVinci "
        "Resolve, Nuke, OCIO-aware DCC). The input and output color spaces "
        "are declared in bundle.json; do NOT apply this LUT to a signal in "
        "a different color space."
    )


@dataclass(frozen=True)
class ColorSpaceMeta:
    """One end of the bundle's color-space contract."""
    name: str
    cctf: bool  # True if the wire carries an encoded (CCTF-applied) signal


@dataclass(frozen=True)
class StocksMeta:
    """Stock identifiers used to build the bundle."""
    film: str
    prints: tuple[str, ...]  # one entry for 1lut, >=1 otherwise


@dataclass(frozen=True)
class WiresMeta:
    """Per-bundle wire constants for the four internal taps.

    Entries can be ``None`` for topologies that don't expose the
    corresponding tap (e.g. 1lut bundles need none of these
    because the intermediate taps aren't materialized as separate LUTs).
    """
    log_e_film: LogEWire | None = None
    cmy_film: DensityWire | None = None
    log_e_print: LogEWire | None = None
    cmy_print: DensityWire | None = None


# LUT role taxonomy emitted by the builder. Centralized so consumers
# (notably ``ocio_emit`` for chain composition) can branch by frozenset
# membership instead of string-matching, and so the docstring on
# :class:`LutFileMeta` doesn't drift from what the builder writes.
SHARED_LUT_ROLES: frozenset[str] = frozenset({
    "film",
    "filming_expose",
    "filming_develop",
})
"""Roles that appear at most once per bundle (shared across all prints)."""

PER_PRINT_LUT_ROLES: frozenset[str] = frozenset({
    "combined",
    "print",
    "printing_combined",
    "printing_expose",
    "printing_develop_scan",
})
"""Roles that appear once per print in the bundle."""


@dataclass(frozen=True)
class LutFileMeta:
    """One LUT entry within a bundle.

    ``role`` values currently emitted by the builder:

    - ``"combined"`` — single full-chain cube (1-LUT topology).
    - ``"film"`` / ``"print"`` — 2-LUT pair.
    - ``"filming_expose"`` / ``"filming_develop"`` — shared L1 / L2.
    - ``"printing_expose"`` / ``"printing_develop_scan"`` — per-print L3 / L4 (4-LUT).
    - ``"printing_combined"`` — collapsed back-half in 3-LUT.
    - ``"subchain_<ids>"`` — opt-in pre-collapsed sub-chain cubes
      (n130), e.g. ``"subchain_12"``, ``"subchain_1234"``.

    The shared-vs-per-print classification lives in
    :data:`SHARED_LUT_ROLES` and :data:`PER_PRINT_LUT_ROLES`.
    """
    role: str
    path: str            # relative to the bundle root
    domain: str          # source tap name (e.g. "input_rgb", "cmy_film")
    range: str           # destination tap name (e.g. "cmy_film", "output_rgb")
    print_profile: str | None = None  # set for per-print roles


@dataclass(frozen=True)
class InputExposureMeta:
    """Bundle-level record of the active input exposure gain (n150).

    Stored on :class:`BundleMeta` whenever the bundle was baked with
    a non-``None`` ``BundleSpec.stops_above_midgray``. Consumers reading
    ``bundle.json`` see both the requested target and the resulting
    linear gain so they can reverse the operation if needed. Omitted
    (the ``BundleMeta.input_exposure`` field stays ``None``) when the
    bundle used the native input dynamic range.
    """
    stops_above_midgray: float
    gain: float  # linear multiplier applied to post-decode_cctf values


@dataclass
class BundleMeta:
    """The full ``bundle.json`` payload."""
    schema_version: int = SCHEMA_VERSION
    name: str = ""
    topology: str = "1lut"  # "1lut" | "2lut" | "3lut" | "4lut"
    resolution: int = 33
    target: str | None = None  # delivery target name, if any
    provenance: ProvenanceMeta = field(default_factory=ProvenanceMeta)
    stocks: StocksMeta | None = None
    color_spaces: dict[str, ColorSpaceMeta] = field(default_factory=dict)
    wires: WiresMeta = field(default_factory=WiresMeta)
    luts: tuple[LutFileMeta, ...] = ()
    input_exposure: InputExposureMeta | None = None
    params_snapshot: dict[str, Any] = field(default_factory=dict)
    """Per-print snapshot of the runtime configuration the LUT creator
    passes to the pipeline — what `RuntimePhotoParams` ran on for each
    bake, *not* a GUI-state dump. Keyed by print profile name; each
    value is a dict of all the LUT-creator-configurable knobs (film +
    print profiles, color-space primaries, CCTF flags, gamut
    compression specs, exposure gain, gamut clip, resolution,
    topology). Profile data on disk (film/print JSON) is identified
    by name; the resolved curves and sensitivities aren't dumped here
    because they'd bloat bundle.json and are reproducible from the
    profile name + spektrafilm version."""
